### ISSUE TITLE
Store symptom tracking information

### ISSUE THREAD

**Issue by leowrites** [uoftblueprint/the-period-purse-2023#23]
Now we have the buttons that allows the user to choose which symptoms they want to track, the next step is to make the symptoms persistent.

- [x] Look into different ways we can store information without a database, something you can try is [SharedPreferences](https://stackoverflow.com/questions/6826735/how-to-store-persistent-data-easily-without-using-databases)
- [x] Create an `User` entity that we would use to store user data
- [x] Depending on how we would access the data, create a user DAO

**Comment by Manpreet-Bhatti** [comment]
The most accessible data storage options (not including databases) found would definitely be SharedPreference, internal/file storage, and external storage.

SharedPreference is great to save primitive data given it's modelled as key-value pairs. These shared preferences are stored in an XML file in a private directory (so relatively safe). You're allowed to have more than one shared preference file which is usually used to store app preferences. Some downsides are: manually need to switch to background thread, cannot signal errors, not safe from runtime exceptions, and doesn't have transactional API with consistency.

To rectify the above discrepancies, preferences DataStore can be used. It's a replacement for SharedPreference with more capabilties. It also uses Kotlin flow so the data emitted from it are cold stream which means until somewhere data is collected it will not emit the stored value. In addition, Kotlin flow can be used as liveData using asLiveData() so in this way, you can also make it lifecycle aware

Internal/file storage is also another great option and can be used sort of as a stepping stone when SharedPreference is too limiting, such as persisting objects and images. This option is great for persisting data in a logical way when dealing with the file system hierarchy. Other apps and users will not have access to this data, and best of all, it deletes when you delete the app itself.

The least "suggested" in my opinion would be the external storage option. A newly updated option, Google allowed apps to have a default option to have scoped access to external storage. This means tapping into a specific directory on external storage and the media that the app creates. To actually use this option though, requires the right permissions from the manifest file. The huge downside is that external storage is not accessible at all times; sometimes it's existent on a removable SD. This means checking the availability of the external storage directories and files.

https://medium.com/theleanprogrammer/all-types-of-storage-you-can-use-in-your-android-kotlin-app-dd2163eded30
https://medium.com/swlh/preferences-datastore-in-a-kotlin-way-4c4c41a906e1
https://developer.android.com/training/data-storage#filesExternal
https://developer.android.com/topic/libraries/architecture/datastore
