### ISSUE TITLE
Organize Repo, Add Java Doc, Refactor Code & Final Clean Up

### ISSUE THREAD

**Issue by leowrites** [uoftblueprint/the-period-purse-2023#55]
See
- [ ] #126 for code refactoring
- [ ] #145 for adding java doc
- [x] #125 for reorganizing repo

**Comment by leowrites** [comment]
Delayed until next release
